FROM tensorflow/tensorflow:2.17.0-gpu

RUN pip install --upgrade pip 

RUN pip install nltk
RUN pip install spacy
RUN pip install transformers

RUN pip install ipykernel

RUN pip install sentence-transformers
RUN pip install tf-keras